"""create update tables

Revision ID: b033990c3b64
Revises: d0c0a49b9c3e
Create Date: 2026-01-08 20:06:41.699995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b033990c3b64'
down_revision: Union[str, Sequence[str], None] = 'd0c0a49b9c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add column as nullable to existing data
    op.add_column('competencies', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='1'))
    
    # Update existing records to set default value
    op.execute("UPDATE competencies SET is_active = 1 WHERE is_active IS NULL")
    
    # Now make it NOT NULL (optional - Oracle allows nullable Boolean)
    # op.alter_column('competencies', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competencies', 'is_active')
    # ### end Alembic commands ###
