"""Auto migration

Revision ID: f8e0464c7a8b
Revises: b033990c3b64
Create Date: 2026-01-10 15:48:10.465823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e0464c7a8b'
down_revision: Union[str, Sequence[str], None] = 'b033990c3b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objectives', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('objectives', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objectives', 'is_deleted',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('objectives', 'deleted_at')
    # ### end Alembic commands ###
